GET http://localhost:3000/subscribers

### 
GET http://localhost:3000/subscribers/235

### 
POST http://localhost:3000/subscribers 
Content-Type: application/json

{
    "name": "Amazing Person", 
    "subscribedToChannel": "Web Dev Simplifile"
}

### 
DELETE http://localhost:3000/subscribers/623aa4a4b4384f56cddb7d40

### PATCH http://localhost:3000/subscribers/623aa6c2b4384f56cddb7d49 Content-Type: application/json

{
"subscribedToChannel": "Camping"
}

### POST http://apitest07.app.ruk-com.cloud/subscribers Content-Type: application/json

{
"name": "Homer Simpson", "subscribedToChannel": "Beers"
}

### GET http://apitest07.app.ruk-com.cloud/subscribers*/